version: "3.7"

services:

  docker-ubuntu-rpa:
    image: delpinos/docker-ubuntu-rpa
    container_name: docker-ubuntu-rpa
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - external-net
    restart: always
    privileged: true
    tty: true

networks: 
    external-net:
      driver: bridge